# Generated by Django 5.1.1 on 2025-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='health',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='health',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='health',
            name='visit_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='health',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='health',
            name='date',
        ),
    ]
