# Generated by Django 5.1.1 on 2025-05-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_health_unique_together_health_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='mail',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
