# Generated by Django 5.1.1 on 2025-05-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_health_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='description',
            field=models.TextField(default='', max_length=50),
        ),
    ]
