# Generated by Django 5.1.1 on 2025-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_petnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
